SELECT * FROM INV_EDITOR;
SELECT * FROM JOURNAL_ISSUE;
SELECT * FROM JOURNAL_VOLUME;
SELECT * FROM BORROWS;
SELECT * FROM WRITES;
SELECT * FROM BOOK;
SELECT * FROM PROCEEDINGS;
SELECT * FROM COPY;
SELECT * FROM DOCUMENT;
SELECT * FROM READER;
SELECT * FROM BRANCH;
SELECT * FROM PUBLISHER;
SELECT * FROM CHIEF_EDITOR;
SELECT * FROM AUTHOR;
SELECT * FROM RESERVES;

#Search a document by ID, title or publisher name.
SELECT * FROM DOCUMENT WHERE DOCID = '';
SELECT * FROM DOCUMENT WHERE TITLE like '%abc%';
SELECT * FROM DOCUMENT WHERE PUBLISHERID in (SELECT PUBLISHERID FROM PUBLISHER where PUBNAME like '%abc%');

#Copies by Docid
select * from copy where docid = '';

#Borrowed Books by Reader
SELECT * FROM BORROWS WHERE READERID= '' and RDTIME is NULL;

#Document status
SELECT * FROM RESERVES WHERE DOCID='';
SELECT * FROM BORROWS WHERE DOCID='';

#List of documents reserved by a reader.
SELECT * FROM RESERVES WHERE READERID = '';

#List of documents borrowed by a reader and their status.
SELECT * FROM BORROWS WHERE READERID = '';

#Print the document id and document titles of documents published by a publisher.
SELECT D.DOCID, D.TITLE FROM DOCUMENT D, PUBLISHER P WHERE D.PUBLISHERID=P.PUBLISHERID AND P.PUBNAME='';

#Add Document copy
INSERT INTO DOCUMENT (DOCID, TITLE, PDATE, PUBLISHERID) VALUES ();

#Add new reader.
INSERT INTO READER (READERID, RTYPE,RNAME, ADDRESS) VALUES ();

#Print Top 10 most frequent borrowers in a branch.
SELECT READERID, LIBID, (SELECT LNAME from Branch where LIBID = B.LIBID) AS BRANCHNAME, COUNT(*) FROM BORROWS B GROUP BY READERID, LIBID ORDER BY COUNT(*) DESC LIMIT 10;

#Print top 10 most borrowed books in a branch.
SELECT DOCID, LIBID, (SELECT LNAME from BRANCH where LIBID = B.LIBID) AS BRANCHNAME, COUNT(*) FROM BORROWS B GROUP BY DOCID, LIBID ORDER BY COUNT(*) DESC LIMIT 10;

#Print the 10 most popular books of the year.
SELECT DOCID, COUNT(*) FROM BORROWS WHERE YEAR(BDTIME) = 2019 GROUP BY DOCID ORDER BY COUNT(*) DESC LIMIT 10;